# Introducción {-}

Kaneko Fumiko (1903-1926) fue una anarquista japonesa que vivió a principios del siglo XX. Nacida ilegitimamente y en una pobreza extrema, vivió su vida como una paria en la sociedad japonesa, incluyendo un periodo en que vivió en la entonces ocupada Corea bajo la tutela de parientes que cuando no indiferentes, fueron crueles con ella. Sus experiencias inspiraron tanto su rebelión contra la autoridad, como sus sentimientos de solidaridad con tode aquelle marginade de la sociedad. Junto a su amigo, pareja y antes de su muerte, esposo, Pak Yol, inició sociedades anarquistas clandestinas; publicó artículos contra el estado y la sociedad del Japón imperial y tal vez, planificó matar al emperador Taisho y al entonces príncipe heredero Hirohito el día de su casamiento.

Ella y Pak eran algunes de les muches que serían arrastrades por los arrestos y asesinatos masivos de enemigues del estado, tanto reales como percibides después del [Gran Terremoto de Kanto de 1923](https://es.wikipedia.org/wiki/Gran_terremoto_de_Kant%C5%8D). Bajo "custodia protectora", ella y Pak fueron juzgades y condenades a muerte por alta traición en cargos relacionados con un complot para matar al emperador y al príncipe heredero. Si bien estas sentencias fueron conmutadas posteriormente a cadena perpetua por el emperador, Fumiko rechazó este honor rápidamente al romper el decreto en la cara de sus carceleros. Poco tiempo después, en 1926, la encontraron colgada en su celda, por lo que se difundió que había cometido suicidio.

Estas transcripciones de los interrogatorios de Fumiko Kaneko proporcionan una mirada valiosa a sus pensamientos y a los hechos de su vida más allá de la época de su juventud detallada en *The Prison Memoirs of a Japanese Woman*, una memoria que escribió durante su juicio. En algunos momentos la vemos discutiendo sus filosofías sobre el nihilismo y la individualidad, el dualismo, la influencia de Stirner que se asoma en su protesta contra el "fantasma" del altruismo confuciano y la insistencia de que les marginades deberíamos ser el centro de todas las cosas. Sus denuncias al emperador y al estado japonés también son conmovedoras aunque la esencia del complot para el asesinato que presenta fuertemente en el segundo interrogatorio incluido acá es bastante confuso porque, como observa Helene Bowen Raddeker (1997); durante sus interrogatorios, probablemente habría inflado su papel para parecer más culpable y ser sentenciada tan severamente como Pak. De esta forma, aunque en la primera entrevista de 1925 (tambien presentada en esta publicación) habla de un intento fallido de Pak para conseguirle explosivos en Corea, más tarde, en 1926, se desmiente y admite que se enteró del intento de Pak solo después de que éste volviera de Corea[^1]. Sin embargo, trasladó su réplica al sistema imperial japonés al trato con los interrogadores de forma tan feroz que la mantuvieron en la carcel, incluso después de dicha admisión.

Este panfleto incluye tres interrogatorios: el primero está extraído de *Reflections on the Way to the Gallows* ("Reflexiones en el Camino a la Horca") de Hane Mikiso que incluye el testimonio de Fumiko Kaneko sobre cómo llegó a dar con su filosofía nihilista, así como la denuncia al sistema imperial japonés y al emperador; el segundo y el tercer interrogatorio, traducidos por Max Res, tienen lugar dos años más tarde que el primero y fueron extraídos por Kurihara Yasushi en su compilación de escritos anarquistas japoneses, *Kurizake* ("Libertad"). Estos incluyen denuncias más contundentes al emperador y a la sociedad japonesa. Aparte de estos textos existe una transcripción completa de los juicios, correspondencias e interrogatorios de Fumiko y Pak en registros judiciales que también se han publicado pero que actualmente están fuera de nuestro alcance. También existen algunos escritos de Fumiko previos al juicio, aunque en un número limitado, y prácticamente todo esto, con la excepción de *The Prison Memoirs of a Japanese Woman*, sigue sin traducirse.

Además de *The Prison Memoirs of a Japanese Woman*, hay otros recursos en inglés para obtener más información sobre Fumiko, que incluyen las mencionadas *Reflections on the Way to the Gallows*, que contiene una traducción de su ensayo *Nani ga watakushi o kō saseta ka" ("Qué me llevo a hacer lo que hice").

*Treacherous Women of Imperial Japan* de Radikker relata y analiza las historias de Fumiko y Kanno Suga, otra anarquista japonesa ejecutada 15 años antes bajo el cargo de traición e incluye un perfil más robusto de la vida de Fumiko. La familiaridad de Raddeker con el anarquismo, Stirner y Nietzsche y el acceso a una amplia variedad de material fuente carga de valor la lectura. El tanka que abre esta publicación también está extraido de allí (Raddeker 232).

Max Res, día de año nuevo de 2020

[^1]: Raddeker, Helene Bowen. *Treacherous Women of Imperial Japan: Patriarchal Fictions, Patricidal Fantasies*. Routledge, 1997.
