# 22 de noviembre de 1923 {-}

[Los siguientes son extractos del interrogatorio de Kaneko del 22 de noviembre de 1923][^2]

Pregunta: ¿Por qué abrazó el nihilismo?

Respuesta: Por las circunstancias de mi familia y las consiguientes opresiones sociales que sufrí.

P: ¿Y su familia?

R: No tengo familia a decir verdad ... Mis padres me abandonaron y me separaron de mis hermanos y hermanas. No tuve vida familiar. Mi nacimiento no fue registrado, por lo que toda la vida fui sistemáticamente oprimida por la sociedad. Es culpa del sistema social... [Después de venir a Tokyo] leí los escritos de Toshihiko Sakai y revistas socialistas. Al ver esto, mis padres se preocuparon. Me incliné hacia el socialismo. Aproximadamente en 1922 conocí a un coreano, Pak Yeol, quien era desconocido y carecía de cualquier tipo de propiedad. Decidí vivir con él y puse al tanto a mis padres sobre esto... Después de que comencé a vivir con él, mi padre me escribió una carta, en mayo de ese año, alegando que yo era descendiente de un canciller del reino, Fujiwara-no-Fusame [681-737] que había vivido hace más de cien generaciones. Me dijo que estaba mancillando el ilustre linaje de la familia Saeki viviendo con un humilde coreano. De esa forma me hizo saber que me desheredaba y que en adelante no debería pensar en él como mi padre. Entonces fui desheredada por mi padre, que ya me había abandonado. Mi madre también me abandonó... Ella incluso en un momento consideró la posibilidad de venderme a como esclava sexual... Mis padres no me dieron amor y sin embargo, trataron de obtener todo el beneficio que pudieron a cuesta mío. El suyo fue un amor verdaderamente egoísta, una forma de codicia. Así que yo, objeto de la codicia, no entiendo el significado de la piedad filial. La moral se basa en la relación entre el fuerte y el débil. Esa moralidad es siempre manipulada para servir a la conveniencia de los fuertes. Es decir, el fuerte insiste en preservar su libertad de acción exigiendo la sumisión de los débiles. Desde el punto de vista de los débiles, la moralidad significa un acuerdo que exige la sumisión de une a los fuertes. Este principio moral es común en todas las edades y en todas las sociedades. El objetivo principal de quienes están en el poder es preservar este principio moral el mayor tiempo posible. La relación entre padres e hijes también está basada en este principio. La expresión "piedad filial" sirve para cubrir esa realidad.

P: ¿Cómo llegó a asociarte con les socialistas y finalmente con el nihilismo?

R: Tres grupos intelectuales me influyeron cuando vendía periódicos ... Uno era un grupo budista de salvación, el segundo fue el grupo del Ejército de Salvación Cristiano y el tercero, los socialistas de pelo largo que gritaban sus consignas con voces desesperadas... Primero me acerqué al Ejército de Salvación.

[Luego relata sus experiencias con Saitō - identificado en sus memorias como Itō. Explica que se desilusionó con el cristianismo cuando dijo que tenía que terminar su amistad con ella porque se había enamorado de ella].

¡Qué tremenda contradicción para unx cristianx predicar el amor en la esquina de la calle y no darle cabida cuando se presenta en su forma más pura! Les cristianes se encadenaron al concepto de Dios que crearon. La suya es una fe cobarde de esclavxs. La virtud y la belleza del ser humane es vivir de forma natural, sin someternse al gobierno de fuerzas externas. Decidí entonces que no podía abrazar el cristianismo, que predica la doctrina de una vida que entra en conflicto con mis ideales de belleza y virtud. Así que abandoné el cristianismo...

[Después se hizo amiga de un socialista, Hori Kiyotoshi, pero se desilusionó de él también porque Hori, afirmó, era un hipócrita. Ocultó su relación con su esposa geisha, por temor a que obstaculizara sus posibilidades de salir adelante en el mundo. También hizo que aquelles debajo de él hicieran todo el trabajo en su imprenta, mientras disfrutaba de su tiempo libre].

También me presentaron a otra socialista, Kutsumi Fusako. Su vida familiar y sus principios no eran muy diferentes a los de Hori. Kutsumi se ocupó de sus propias necesidades personales pero no le prestó atención a las necesidades de sus hijes. Siempre encontraba alguna excusa para salir con un hombre joven y quedarse fuera todo el día. Una vez la escuché decir que todo lo que tenía que hacer era subir a una plataforma, dar un discurso sobre el socialismo y decir “Hay que destruir la sociedad actual” para provocar una intervención de la policía. Al día siguiente, los periódicos informarían que Kutsumi Fusako dio un discurso extremista, por lo que la policía le impidió hablar. Siempre me disgustó el deseo generalizado entre los socialistas de que sus nombres aparezcan en el periódico. En este momento, Kutsumi no tenía dinero ni siquiera para comprar comida, por lo que empeñó mi ropa sin mi permiso. Luego dejó que el período de rendición expirara y permitió que el empeño se vendiera. No me quejo de perder mi ropa, aunque ella sabía que la necesitaba porque había llegado el invierno. Ella no mostró ningún sentido de responsabilidad. Yo detestaba su actitud, una socialista que supuestamente estaba comprometida con las necesidades ajenas, pero que pensaba solamente en alimentarse a sí misma.

Yo me imaginaba que les socialistas eran personas que se elevaban por encima de las costumbres y la moral sin sentido que impone la sociedad. Les imaginé como luchadores valientes sin interés de inflar su propio ego y la supuesta fama que viene de la reputación social. Pensé que eran guerreres que luchaban para destruir esta sociedad perversa y se esforzaban por crear una distinta. Sin embargo, a pesar de que hacen una denuncia de las injusticias e hipocrecías de la sociedad, y aparentan ser indiferentes a la fama y a la reputación, de hecho se rigen y se preocupan por los estándares vigentes en la sociedad que dicen repudiar. Buscan adornarse con ornamentos convencionales y reproducen los valores convencionales. Así, como los generales se enorgullecen de las medallas condecorativas en sus pechos, les socialistas codician registros de arresto para ganarse el pan. Se enorgullecen de esto. Cuando me di cuenta de este hecho, me alejé.

También llegué a horrorizarme por la somnolencia de les campesines, que están sumides en el dolor pero no sienten dolor, y la ignorancia de les trabajadores, que trabajan diligentemente mientras son devorades hasta los huesos. Si se les quitan las cadenas que les atan, es probable que vayan a los portadores del poder político y económico con sus cadenas a suplicarles que vuelvan a encadenarles. Quizás sean más felices si se les permite simplemente dormir en la ignorancia. Así que me disgusté de todas las corrientes de pensamiento y desde la primavera de 1922 abrazé con fuerza las creencias nihilistas que sostengo hoy.

En cuanto al significado de mi nihilismo ... en una palabra, es la base de mis pensamientos. El objetivo de mis actividades es la destrucción de todos lo vivo. Siento una ira ilimitada contra la autoridad parental que me aplastó bajo el nombre altisonante del amor paterno, y contra el estado y la autoridad social, que abusó de mí en nombre del amor universal.

Habiendo observado en la realidad social el hecho de que todxs lxs seres vivxs de la tierra están incesantemente comprometidxs en una lucha por la supervivencia, que se matan entre ellxs para sobrevivir, llegué a la conclusión de que si hay un absoluto, una ley universal en la tierra, es la realidad de que los fuertes explotan a los débiles. Esta creo, es la ley y la verdad del universo. Ahora que he visto la verdad sobre la lucha por la supervivencia y el hecho de que los fuertes siempre ganen y los débiles siempre perdamos, no puedo unirme a las filas de les idealistas y adoptar un modo de pensar optimista que sueña con la construcción de una sociedad sin autoridad ni control. Mientras todo lo vivo no desaparezca, las relaciones de poder basadas en el principio de la explotación persistirán. Porque los portadores del poder van a hacer todo lo que esté a su alcance para defender su autoridad de la manera habitual, oprimiendo a los débiles, y porque mi experiencia pasada ha sido una historia de opresión por parte de toda las formas de autoridad decidí negar los derechos reclamados por toda forma de autoridad, rebelarme contra ellos, poniendo en juego no sólo mi propia vida sino la de toda la humanidad en este empeño.
Por esta razón planeé eventualmente lanzar una bomba y aceptar el fin de mi vida. No me importaba si este acto desencadenaba una revolución o no. Estoy perfectamente contenta de satisfacer mis propios deseos. No quiero ayudar a crear una nueva sociedad basada en una nueva forma de autoridad.

P: ¿Cuál es su opinión sobre el sistema estatal y social japonés?

R: Divido el sistema social estatal japonés en tres niveles: la primera clase son los miembros del clan real, la segunda clase son los ministros del gobierno y otros detentores del poder político y la tercera clase son las masas en general.

Considero a la primera clase, el clan real, como víctimas lamentables que viven como presxs, cuyas idas y venidas, al igual que en el caso del regente imperial, están estrictamente reguladas. Pienso que elles son marionetas lamentables y muñecos de madera que están siendo manipulados por la segunda clase, el verdadero portadores del poder, con el fin de poner el velo sobre los ojos de las masas. La tercera clase, la las masas, como mencioné antes, son ignorantes más allá de la salvación. La segunda clase, los portadores del poder político, son los que tienen el poder real para perseguir a les débiles como yo. Razón por la que no siento nada más que un profundo y amargo odio hacia esta clase. Mientras que en realidad la segunda clase es la poseedora real del poder, la primera clase es la poseedora formal del poder. Entonces estas dos clases van de la mano. Consecuentemente coloco la segunda clase en el nivel secundario y dirijo mis sentimientos rebeldes contra la primera clase. Aunque también contemplé realizar ataque [lanzar bombas] contra ambas clases.
Pak Yeol y yo hablamos de esto.

Llevo un diario de mis días en prisión. El 6 de noviembre escribí: “Los derechos del pueblo están siendo lanzados como pelotas de mano por los que ejercen el poder. El gobierno, los funcionarios del gobierno finalmente me han metido en la cárcel. Pero he aquí mi consejo para ellos: si desean evitar que el incidente actual dé frutos, deben matarme. Pueden mantenerme en la cárcel durante años y tan pronto como salga, voy a volver a intentarlo. Destruiré mi propio cuerpo y les evitaré la molestia. Pueden llevar este cuerpo mío a donde quieran, a la guillotina si lo desean o a la prisión de Hachiōji. Todos tenemos que morir eventualmente. Así que pueden hacer lo que quierasn. Solo estarán probando que viví fiel a mí misma. Estoy perfectamente feliz con eso ". Esperan que me comprometa con ustedes, cambie mi forma de pensar y viva en conformidad con los pactos de la sociedad. Si pudiera comprometerme con ustedes ahora, me habría comprometido con usted cuando estaba en libre. No vengan a predicarme con eso. Tengo suficiente noción como para entenderlo. Estoy preparada para lo que sea que me hagan. Así que hagan lo que quieran. No lo duden. A decir verdad, me gustaría salir al mundo una vez más. Sé que todo lo que tengo que hacer es decir "He cambiado de opinión" e inclinar la cabeza. Pero no puedo negar mi yo actual para que mi yo futuro pueda sobrevivir.
Oficiales, permítanme proclamarles valientemente una vez más: “En lugar de inclinarme ante los portadores del poder, prefiero morir y ser fiel a mí misma. Si esto no les agrada, pueden arrebatarme la vida en cualquier forma que deseen. No tengo miedo de nada de lo que puedan hacerme ". Esta es la forma de senir que desarrollé en el pasado y así es como me siento ahora.
P: ¿Conoció a Pak Yeol después de desarrollar esta forma de pensar?
R: Eso es correcto. Después de conocer a Pak, hablamos sobre nuestras ideas y descubrimos que nuestras opiniones eran similares. Entonces, para trabajar juntes, comenzamos a vivir juntes[^3].

[Durante el curso del interrogatorio, Kaneko reveló su opinión sobre el sistema imperial japonés con franqueza].

Incluso antes de conocer a Pak Yeol, creía que el emperador era una entidad inútil. Pak y yo nos juntamos porque estuvimos de acuerdo en eso. Nos unimos como camaradas para derrocar al sistema del emperador. Por naturaleza, les seres humanes deberíamos ser iguales. Y sin embargo, la entidad llamada emperador nos volvió desiguales. El emperador se supone que es augusto y exaltado. Sin embargo, su fotografía muestra que es como nosotres les plebeyes. Tiene dos ojos, una boca, piernas para caminar y manos para trabajar. Pero no usa sus manos para trabajar, ni sus piernas para caminar. Esa es la única diferencia. La razón por la que niego la necesidad del emperador se levanta de mi creencia de que les seres humanes somos iguales.

Se nos ha enseñado que el emperador es descendiente de los dioses y que su derecho a gobernar le ha sido otorgado por esxs seres superiores. Pero estoy convencida de que la historia de los tres sagrados tesoros [la espada, el espejo y la joya, que descienden de la era de los dioses como emblemas de la autoridad imperial] es simplemente un mito arrancado de la nada. Si el emperador fuera un dios, entonces sus soldados no morirían ¿Por qué decenas de miles de súbditos reales fueron asesinados por el gran terremoto en su presencia inmediata? Tenemos entre nosotres a alguien que se supone que es un dios viviente, uno que es omnipotente y omnisciente, un emperador que se supone que debe realizar la voluntad de los dioses. Sin embargo, sus hijos lloran de hambre, mueren asfixiados en las minas de carbón, y mueren aplastades bajo las máquinas de las fábricas. ¿Por qué esto es así? Porque en verdad el emperador es un mero ser humano. Queríamos mostrarle a la gente que el emperador es un ser humano ordinario como nosotres. Así que pensamos en lanzar una bomba en el desfile para mostrar que él también morirá al igual que cualquier otre ser humane.
Se nos ha enseñado que la política nacional japonesa consiste en un linaje ininterrumpido de familia imperial a lo largo de los siglos. Pero la genealogía imperial es realmente confusa. E incluso si la genealogía es ininterrumpida a través de los siglos, no significa nada. No es nada de lo que estar orgulloses. Incluso es bastante vergonzoso que les japoneses hayamos sido tan ignorantes como para consentir que se nos impongan bebés como emperadores.
Bajo el sistema imperial, la educación, las leyes y los principios morales fueron ideados para proteger la autoridad imperial. La noción de que el emperador es sagrado y augusto es una fantasía. Le hicieron creer a la gente que el emperador y el príncipe heredero representan autoridades sagradas. Pero son simplemente marionetas vacías. Los conceptos de lealtad al emperador y amor a la patria son simplemente nociones retóricas que están siendo manipuladas por el grupo minoritario de las clases privilegiadas para satisfacer su propia codicia e intereses[^4].

[^2]: Esta traducción, que incluye paráfrasis y notas a pie de página, se puede encontrar en _Reflections on the Way to the Gallows: Rebel Women in Prewar Japan_ de Mikiso Hane.
[^3]: Archivo de la corte distrital de interrogatorios de Tokyo, 22 de noviembre de 1923.
[^4]: Setouchi Harumi, ed., *Onna no Isshō, Jimbutsu Kindai Joseishi, Hangyaku no Onna no Roman*, 8 vols. (Tokyo: Kōdansha, 1980), VI: 168-69.

