# 14 de mayo de 1925 {-}

[52° Registro de interrogatorios, 14 de mayo de 1925, Prisión de Ichigaya. Este es el primer interrogatorio desde que fue acusada de cargos adicionales].

(La apertura del interrogatorio fue omitida)

Pregunta: ¿Es correcta su afirmación de la última vez de que la idea de pedirle a Kim Han explosivos para usarlos durante el casamiento del príncipe heredero surgieron de tus conversaciones con Pak?

Respuesta: Es correcto.

P: ¿Es correcto también que le pidió explosivos a Kim Han también como preparación para la el casamiento del príncipe heredero?

R: Me enteré que celebrarían una ceremonia de boda para el príncipe en un futuro cercano. En esa época Pak fue a Gyeongseong para ponerse en contacto con Kim Han. Recuerdo que en ese momento no se había decidido con firmeza la fecha de la boda del príncipe. En cualquier caso, había anticipado que la procesión de la boda se llevaría a cabo en un futuro próximo. Lo recuerdo. Debido a esto, Pak fue a Gyeongseong para que yo tuviera una bomba a tiempo para este increíble oportunidad de atacar durante la procesión.

P: ¿Hubo alguna discusión entre usted y Pak cuando se fue a Gyeongseong sobre poder llegar a tiempo para la ceremonia de la boda?

R: Hablé continuamente con Pak acerca de plantarle una bomba al joven príncipe durante la ceremonia de boda imperial. Si eso fue algo que sucedió antes de irse a Gyeongseong, o si fue después, no puedo recordarlo claramente en este momento. En cualquier caso, debido a que desde el momento en que Pak se fue a Gyeongseong, pensé que usar una bomba en la ceremonia de la boda era lo mejor, creo que Pak probablemente le dijo a Kim Han que nos diera una bomba a tiempo.

P: Después de regresar de Gyeongseong, ¿Pak le dijo que había hablado con Kim Han sobre tener bombas a tiempo para la boda?

R: Nunca supe si Pak había tenido ese tipo de conversación. Lo único que me dijo después de regresar de Gyeongseong fue que Kim Han finalmente estaría compartiendo las bombas con nosotres.

P: En ese caso, desde el momento en que Pak regresó de Gyeongseong a fines de 1922, ¿Discutieron sobre la dificultad de conseguir bombas de Kim Han debido al incidente de Kim Sang-ok[^5] y sobre usarlas en la ceremonia una vez que las obtuvieran?

R: Pak y yo tuvimos muchas conversaciones sobre el uso de bombas en la ceremonia, pero no recuerdo bien si sucedieron en ese momento o cuando.

P: ¿Qué pasó en el momento de su involucramiento con Kim Jun-han?[^6]

R: Recuerdo claramente que en ese momento hubo una conversación entre Pak y yo sobre el uso las bombas en la procesión.

P: ¿A quién le iban a tirar las bombas?

R: En última instancia, seríamos felices siempre que pudiéramos hacérselas llegar al principito. También sería bueno matar al emperador, pero la procesión era una oportunidad única y dado que el emperador es un hombre enfermo, el valor de la acción de matarlo sería diferente. No valdría la pena. Así que apuntamos al príncipe.

P: Una vez que obtuvieron las bombas, ¿quién se suponía que las tiraría?

R: Por supuesto que Pak y yo, pero también pensé en preguntarle a otres compañeres como Nīyama, Choi Gyujong y Yamamoto Katsuyuki para hacerlo. La idea que tenía en mente era que, debido a que Nīyama y Yamamoto estaban preocupades por problemas de salud desde hacía tiempo y estaban preparades para morir, y Choi es el tipo de persona que una vez involucrado, es capaz de llevar a cabo cualquier tipo de acción directa. 
Pak y yo podríamos hacer que estos tres se dividieran y tiren bombas en lugares como *Diet Mitsukoshi*[^7] , el cuartel general de la policía y el palacio imperial al mismo tiempo que nosotres estubiéramos haciendo lo propio.
Pero luego, en lo que respecta a Nīyama, después de que ella se involucrara en una relación romántica con Kim Jun-han nos pareció que no era lo mejor involucrarla para este tipo de acción directa y abandonamos definitivamente el plan para recurrir a otres compañeres.

P: ¿Lanzar una bomba al príncipe heredero era su único objetivo?

R: Al final, hubiéramos sido felices simplemente matando al principito, pero si pudiéramos, nos hubiera gustado matarlo junto con el primer ministro y otros verdaderos poseedores del poder político. Pero como estuvimos lentxs para aprovechar la oportunidad una vez que tuviéramos las bombas en nuestras manos, y si hubiéramos sido atrapades por la policía nos habríamos visto realmente estúpides, como yo ahora mismo sentada acá; consideramos que si realmente no tuviéramos la oportunidad de lograrlo, pondríamos nuestros ojos en la posibilidad de mandar un mensaje, y consideramos tirar las bombas durante eventos como las celebraciones del Primero de Mayo o la apertura de *Diet Mitsukoshi*.

P: ¿Pak tenía la misma intención principal de lanzar una bomba a su majestad?

R: Si.

P: ¿Por qué intentó causar tanto daño al príncipe heredero?

R: Durante mucho tiempo he pensado profundamente que todes les humanes somos iguales. Siendo todes humanes, ellos deberían ser lo mismo. En ese sentido, no habría diferencia en relación a capacidades, ser fuerte o débil. Como humanes creo que todes somos completamente iguales en valor, y siguiendo de la única cualificación de ser humanes, todes debemos poder gozar del derecho a toda actividad y posibilidad humana.
Para decirlo de manera concreta, todas las acciones que se han realizado, se están realizando y pueden ser realizadas por humanes. Se construyen sobre la base de nuestra humanidad. Por tanto, creo que todas estas acciones, construidas sobre un fundamento natural y realizado por humanes, deben ser reconocidas como iguales en tanto actividades humanas por la única calificación de ser realizadas por seres humanos. Y sin embargo, estas formas de existencia humana están siendo negadas y controladas en nombre de las leyes escritas por otros humanos. Humanos que deberían ser iguales por naturaleza, y sin embargo se encuentran en una situación desigual en esta sociedad. Maldigo esa desigualdad. Hace sólo dos o tres años, pensé en la llamada "nobleza"[^8] de la clase alta como una raza peculiar, dotada de una forma y sustancia en todos los sentidos diferentes de los llamados plebeyos. De hecho, incluso mirando fotografías en el periódico se puede ver que la llamada nobleza no es en modo alguno diferente de la plebe. Tienen dos ojos, una boca, dos piernas para caminar y manos para trabajar, parece que no les faltan atributos humanos en lo más mínimo.
De hecho, no creo que une niñe deforme [sic] que careciera de esas capacidades pudiera jamás formar parte de esa clase. Esta comprensión de, en resumen, la clase de la casa imperial, la comprensión de que cuando hablás de ellos sentís que estás hablando de gente noble e inviolable es algo que probablemente esté arraigado en el corazón de la gente. Para decirlo de otra manera, el estado japonés y los gobernantes se aprovechan de las formas de entendimiento popular.

De entrada, los países, las sociedades, los pueblos y gobernantes no son más que ideas. Sin embargo, para recubrir a los gobernantes de estas ideas de majestad, poder político y santidad, existe en Japón algo que representa lo que acabo de mencionar: el derecho divino de los reyes. Así, a cualquiera nacide en suelo japonés se le inculca esta idea -incluso a les estudiantes en la escuela primaria- con el fin de inculcar en la gente inocente nociones como que el propio emperador desciende de los dioses, o que su derecho a gobernar es algo otorgado por decreto divino, e incluso que el emperador es alguien que controla el poder del estado para realizar la voluntad de los dioses, y así la ley es la voluntad de los dioses; así basan estas cosas en leyendas fantásticas, alardeando y ofreciendo solemnemente alabanzas a cosas como un espejo, una espada y una joya[^9] como si hubieran sido entrgados por los dioses. La pobre gente engañada, envuelta en estas leyendas absurdas, considera que cosas como el gobierno y el emperador son deidades, pero si el emperador es un dios en sí mismo o desciende de los dioses y si la gente fuera por ahí bajo la protección de estos dioses, existiendo bajo los espíritus de generaciones sucesivas de estos dioses-emperadores, ningún soldado japonés debería tener que morir en tiempos de guerra, ningún avión japonés se debería caer del cielo, y algunas decenas de miles de súbditos leales no deberían morir bajo los dominios terrenales de los dioses debido a un desastre natural como el del año pasado[^10].

Pero entonces ¿cómo es que esta cosa fantasiosa convertida en verdad inquebrantable, el derecho divino de los reyes, no cae por su propio peso? ¿Y cómo es posible que sin importar que el emperador sea el todopoderoso y omnipotente, la manifestación y voluntad de los dioses en la tierra; cómo en esta sociedad hay niñes que lloran de hambre, que se asfixian en las minas de carbón y que tienen muertes miserables aplastades bajo maquinria? ¿No es todo esto suficiente evidencia de la verdad? Que el emperador es solo un trozo de carne, alguien que en todos los sentidos es igual al resto de nosotres ¿No deberíamos ser todes igual a él? ¿No fue lo mismo para usted, oficial? A mi me enseñaron en la primaria que porque nuestra única gloria como seres humanos es haber tenido la fortuna de nacer en la nación sin comparación que es este país, donde vivimos bajo un emperador que forma parte de una línea continua e ininterrumpida, tenemos que poner nuestro mayor esfuerzo en realzar esa gloria. Y yo no sé si lo de su pertenencia a una línea de sangre es cierto o no, pero en cualquier caso, ¿cuál es honor de ser gobernades por un solo linaje? He oído hablar antes de un emperador que se ahogó y se convirtió en comida para peces, Antoku[^11] o algo así, al que la responsabilidad de gobernante de Japón se le otorgó cuando era une niñe de solamente dos años. ¿La gloria de les gobernades es realmente jactarse de venerar como su gobernante a un ser humane tan incapaz? Más bien, no por tratarse de une niñe, sino por otorgar a una línea imperial de diez mil años el poder de gobernar incluso como una formalidad, es la vergüenza más profunda de las personas nacidas en suelo japonés, y prueba de nuestra ignorancia.
La tragedia del año pasado, donde muchas personas murieron quemadas a metros del ileso y saludable emperador, fue algo que demostró que en realidad éste es solamente un pedazo de carne y al mismo tiempo, que desprecia la necedad y la ingenuidad de las personas del pasado.

La escuela se esfuerza por enseñarnos, en primer lugar, que la palabra "bandera" existe naturalmente en la tierra y nos inculca el espíritu patriótico. Y una amplia variedad de actividades, todas igualmente válidas en la medida de estar hechas por humanes, se dividen en lo correcto e incorrecto, en lo que está bien y lo que está mal, solamente bajo el estándar único de si siguen o no lo prescripto por la autoridad. Ese estándar son la ley y la moralidad.
La policía, que administra la ley que solo enseña el camino hacia una vida y una sociedad mejor a los vencedores y a aquelles que se someten a la autoridad; baja sus sables y amenazan las acciones humanas, sometiendo a todes quienes puedan sacudir los pilares del poder. Y los jueces, esos funcionarios respetables, hojean los libros de derecho y dictan sentencias arbitrarias sobre las acciones humanas, alienándose de las vidas de las personas que las hacen, negando incluso su humanidad mientras asumen su deber como protectores de la autoridad.
Como cuando el cristianismo estaba en su apogeo y para proteger su santidad, prohibieron la investigación científica por temor a sacudir los pilares de los milagros supersticiosos de dios y así sostuvieron las tradiciones que predicaban.

Cosas como la santidad del estado y la santidad del emperador también son efímeras y se valen de la fuerza para oprimir las ideas y argumentos que los exponen como meras ilusiones.

Así, la tierra está actualmente ocupada y pisoteada por el poder, porque las vidas que deberían ser disfrutadas por les humanes, solamente son consideradas válidas si se someten a él.
Y los representantes del poder que está sometiendo la vida en la tierra, quienes deberían ser semejantes al resto de nosotres, son el emperador y el príncipe heredero. Todas las razones que dí para justificar el ataque al principe proceden de estas ideas.

Y los representantes del poder que pisotean la vida de aquelles que nacimos naturalmente iguales como humanes en la tierra, esos pedazos de carne que son el emperador y el príncipe heredero, obtuvieron su santidad exagerada, sus jerarquías incuestionables, mediante la explotación y el engaño de la gente pobre. Y es ahí que yo quería mostrarle a la gente que aquellos que están siendo envestidos como poseedores de un poder sagrado e incuestionable, el emperador y el príncipe heredero, son en verdad pedazos de carne vacíos, nada más que títeres; quería mostrarle a les explotades que los gobernantes no son más que marionetas y maniquíes ridiculos usados por unos pocos privilegiados para enriquecerse engañando a las personas que generan la riqueza; y a través de esto, mostrar que la montaña de tradiciones de larga data que otorga divinidad al emperador no es más que un montçon de supersticiones. Para mostrar, porque la sustancia vacía de esta nación japonesa que se considera la tierra de los dioses no es más que un sistema provisional para aumentar las ganancias personales de unos pocos privilegiados. La ideología del sacrificio por la nación -a menudo denotada como "lealtad y patriotismo"- que es glorificada, propagandizada e incluso considerada un eslogan nacional, es en verdad nada más que expresión del deseo cruel de sacrificar las vidas de les que menos tienen en beneficio de unos pocos, envolviendo la explotación con adjetivos bonitos como forma de ser autocomplacientes en la satisfacción de los intereses de los explotadores y sus aliados. Puse la mira sobre el príncipe para advertir a la gente que su consentimiento significa estar de acuerdo con ser esclaves de unos pocos privilegiados, para hacer saber a la gente que la moral altruista fundamental exigida por el confucianismo y que les japoneses hasta ahora venimos sostenido como el credo de nuestras vidas, es la moral de esclaves que subyuga nuestros corazones e incluso nos inclina a ser gobernades por una ilusión, por un fantasma vacío. Y haciéndoles saber eso, hacerles notar que deberían actuar enteramente por sí mismes, que les que hacemos el universo son nosotres mismes y que por lo tanto, cada cosa que existe, existe para para nosotres y por nosotres.

En cualquier caso, pensé que al plantar esa bomba, pronto pondría fin a mi vida. La razón por la que apunté al príncipe, que acabo de contar, con la idea de establecer una declaración al mundo, es decir, poner en evidencia algo para la gente, fue de hecho al mismo tiempo, un esquema que me inventé para mantener un mínimo ápice de esperanza y nada más. En otras palabras, era yo extendiendo hacia afuera pensamientos que habían sido dirigidos hacia mí misma, lo que equivale a decir que los pensamientos que me tenían a mí como objeto estuvieron siempre en la raíz de este plan.

En cuanto a los pensamientos que me tienen a mí misma como objeto, lo que sería mi ideología nihilista, ya hablé de esto en detalle la última vez. Para seguir mi plan hasta su conclusión lógica, el objetivo negativo era negar mi propia vida, y el objetivo positivo final, el corazón del plan en sí mismo, fue la destrucción de todo poder en esta tierra.

Por eso apunté al principe.

P: ¿Cómo está su salud física?

R: ¿Mi salud? Eso se resolvió hace mucho tiempo.

P: ¿Se reformó durante este tiempo en la cárcel?

R: No he hecho absolutamente nada de lo que deba arrepentirme. De hecho, se podría decir que mis ideas y acciones, mi plan es malo porque causaría problemas a otras personas, pero al mismo tiempo son cosas de las que yo misma me beneficio.

Ciertamente, juzgar las cosas según tus intereses no está mal; más bien, es la naturaleza humana, una condición para vivir. Si juzgar las cosas de acuerdo con tus intereses fuera malo, la culpa estaría en el hecho de que les humanes estamos vives. Para mí, las cosas que te benefician son buenas y las cosas que te perjudican, son malas.
Pero no llevé a cabo este plan porque creí que era bueno. Solamente lo hice porque quise. Así como no importa cuánto me critiquen por ser mala, no me desvío de mi camino; tampoco me importa cuánto me halaguen por ser buena, si no quiero hacer algo, no hago.

Voy a seguir haciendo cosas porque quiero. No puedo predecir cuáles van a ser esas cosas, pero lo que sí es seguro es que mientras exista voy a hacer las cosas que quiera hacer.

[^5]: Sang-ok fue un miembro de la resistencia a la ocupación japonesa en Corea. Plantó una bomba a la policía de Jongno en Seúl en enero de 1923 y fue asesinado en un tiroteo con la policía unos días después.
[^6]: Kim Jun-han fue un compañero de Fumiko y Pak, participaron juntes de varios grupos radicales y probablemente se distanciaron debido a las discusiones entre él y Pak en agosto de 1923.
[^7]: Hoy en día es una cadena japonesa de grandes shoppings, pero en 1925 era un conjunto de mercados y almacenes.
[^8]: La sociedad Meiji estaba dividida en clases, la nobleza, descendientes de clanes samuráis y plebeyxs.
[^9]: Artículos conocidos como los Tres Tesoros Sagrados (*Sanshu No Jingi*). Según la leyenda, fueron traídos a la 
tierra por Susa-no-O el antepasado de la línea imperial japonesa.
[^10]: En el gran terremoto de Kanto de 1923 se estima que murieron más de 140.000 personas, muches a causa de los incendios que se desataron como consecuencia.
[^11]: Antoku (1178-1185) fue ahogado por su abuela cuando esta, frente al peligro de ser capturada por el clan enemigo Minamoto, saltó por la borda con él en brazos tras la batalla naval de *Dan-no-ura*.