# 18 de julio de 1925 {-}

Primer interrogatorio, 18 de julio de 1925 Cárcel de Ichigaya, Kaneko Fumiko (archivo del interrogatorio).

En cuanto al caso de la imputada mencionada anteriormente, en virtud del artículo 73[^12], así como por la violación de la Ley de control de explosivos, el siguiente interrogatorio tuvo lugar en la Cárcel de Ichigaya el 18 de julio de 1925, siendo llevada a cabo por el juez Tatematsu Kaisei de las Apelaciones de Tokyo, tribunal encargado de la audiencia preliminar bajo el poder especial perteneciente a la suprema corte, y el secretario Okuyama Gunji del mismo tribunal.

Pregunta: ¿Cuál es su nombre?

Respuesta: Kaneko Fumiko.

P: ¿Edad?

R: Oficialmente tengo 24, aunque tengo 22 por lo que recuerdo. Pero para decirte la verdad, no creo en cualquiera. Y lo que es más, no necesito creer. No importa la edad que tenga, no tiene nada que ver conmigo viviendo mi propia vida ahora mismo.

P: ¿Su clase?

R: Un plebeyo divino.[^13]

P: ¿Cuál es su ocupación?

R: Mi trabajo es derribar todo lo que existe actualmente.

P: ¿Lugar de residencia?

R: Cárcel de Tokio.

P: ¿Dirección permanente?

R: Prefectura de Yamanashi, distrito de Higashi-Yamanashi, aldea de Suwa, 1236 Somaguchi.

P: ¿Lugar de nacimiento?

R: Ciudad de Yokohama.

P: ¿Tiene algún rango, condecoración, insignia de servicio militar, jubilación, pensión u oficina pública?

R: No pueden darme nada de eso, e incluso si pudieran, no las tomaría.

P: ¿Alguna vez ha sido condenada por algo?

R: Recibiré una pronto, ¿no es así?

P: ¿Ha leído el documento oficial de cambio de jurisdicción para usted y el otro acusado?

R: Sí.

P: ¿Existen discrepancias con los hechos registrados en ese documento?

R: No las hay.

P: Sobre ese punto, ¿tiene algún comentario sobre el fiscal general que los procesa a usted y a Pak Jun-sik[^14] de esta manera y solicitante de la audiencia preliminar de la Corte Suprema?

[En este momento el juez ha comenzado a leer el apartado titulado “Acusaciones de la Preliminar Solicitud de audiencia"].

R: Sin comentarios.

P: ¿Y sobre le hecho de que yo lleve a cabo la audiencia preliminar por orden del jefe de la suprema corte?

R: No hay objeciones.

P: ¿Hay algún error en lo que dijo en la audiencia preliminar de su caso en el tribunal del distrito de Tokio por violar la ley de la policía de seguridad y la ley de control de explosivos?

R: No los hay.

[^12]: El delito de alta traición segun el código penal Meiji.
[^13]: Radikker (1997) interpreta esta respuesta de Kaneko como un gesto de provocación hacia el estatus divino del Emperador (p234).
[^14]: Nombre de nacimiento de Pak Yol.

